### ISSUE TITLE
Trying to get this working on new Ubuntu install and perhaps dockers

### ISSUE THREAD

**Issue by TRaSH-** [l3uddz/sonarrAnnounced#26]
I'm using this tool without any issues on a old Debian VM,
Now i want to move it all to a Ubuntu VM and perhaps to dockers.
The issue is when i run it on Ubuntu i'm getting the following error.

```
2018-12-29 14:25:34,884 - IRC                  - Exception pool.handle_forever:
Traceback (most recent call last):
  File "/opt/sonarrAnnounced/irc.py", line 83, in start
    pool.handle_forever()
  File "/home/hydra/.local/lib/python3.6/site-packages/pydle/client.py", line 475, in handle_forever
    connections = gather(*connection_list, loop=self.eventloop)
  File "/usr/lib/python3.6/asyncio/tasks.py", line 602, in gather
    fut = ensure_future(arg, loop=loop)
  File "/usr/lib/python3.6/asyncio/tasks.py", line 526, in ensure_future
    raise TypeError('An asyncio.Future, a coroutine or an awaitable is '
TypeError: An asyncio.Future, a coroutine or an awaitable is required
```

Any help what the issue could be or how to solve it
I compared all the files with my Debian install and they are identical.
both running Python 3.6.x

**Comment by 3n8** [comment]
Same here. i am running it in a docker container built on alpine. Not of my own making but made and used with success by others.

**Comment by b000p** [comment]
+3 
This is the one I'm using [https://hub.docker.com/r/stealthgyro/docker-sonarrannounced/]

**Comment by LSL1337** [comment]
DId you manage to solve it?
It drives me crazy for months now.
I have the same docker on the same machine work before. It was working fine for over a year. I tried another container(tonyx) and ever since it doesn't work with either...
Went back to the OLD docker with the old config file and I have the same error you have (on BTN). even on the same unraid machine....
MAKES ZERO SENSE 2me... funny thing is, the 2 different dockers (stealthgyro and tonyx) give 2 different errors...

**Comment by b000p** [comment]
Nope. Was gunna try https://hub.docker.com/r/fryfrog/sonarrannounced made some changes but not got there yet

**Comment by tehconz** [comment]
I'm getting the same errors, in Ubuntu, two different docker containers, even tried it on Windows. Does this work for anyone anymore?

**Comment by Cookiezzz** [comment]
The error you're getting above is because Pydle (the IRC library) switched to asyncio (https://github.com/Shizmob/pydle/pull/106). I fixed mine but then stumbled upon the repo below. That guy fixed the issue and rewrote most of the code. It also supports radarr and a lot more trackers now.

https://github.com/weannounce/arrnounced

**Comment by l3uddz** [comment]
This project is no longer being maintained.

I will update the repo to reflect that.

In the meantime, you can use @Cookiezzz fork - or use the "rewrite" we did in golang with support for all autodl supported trackers:

https://gitlab.com/cloudb0x/trackarr
