### ISSUE TITLE
webui / access

### ISSUE THREAD

**Issue by aroundmyroom** [l3uddz/sonarrAnnounced#3]
with
[server]
host = 0.0.0.0
port = 3467
user = admin
pass = password

I am able to access the webui (dev branch) but question is, I've seen the torrent part is using host as well. now it is not localhost anymore but 0.0.0.0 (most of time to give access to other systems to the webserver as well) but will the URL be correctly be defined to download the torrent from?
cause http:/0.0.0.0:3467/torrent/etc.. will probably not work... 

update to local ip also works, but would love to use domain name

**Comment by l3uddz** [comment]
In the dev branch I have removed entirely the torrent server as it was not required. It simply passes the direct download link to sonarr now so it can download directly from the tracker. The server section in settings.cfg should only affect the webui now. Do let me know if any issues as haven't merged to master yet till I've ran it a week without any problems

**Comment by aroundmyroom** [comment]
not yet any issue (yeah!)..  a number of 12 torrents have been correctly downloaded tonight 
I had what troubles changing username and password (it seems obligatory and if changing in a shell it could be trouble with spaces / or carriagereturns), so that part needs to be tested a little bit more by me
cause it took some time to find out that localhost is really localhost  ;)

btw I do test only one tracker as I have access to only 1

btw after setting the config settings in the GUI do you need to restart the application or is is adapted on-the-fly?

**Comment by l3uddz** [comment]
great. 12 downloaded for me too lol. we must watch same stuff. 
in regards to the config settings. that is something i need to work on to ensure it does change on the fly. 

i know changing the ip/port wont come into effect until a restart, same as the logging options, but things like the server user/pass and other settings should be changed on the fly. do let me know if you find otherwise. ill do some further testing to check this out.

pretty sure tracker setting changes also need a restart - will try to solve that - or provide a way to restart from within the webui

**Comment by aroundmyroom** [comment]
20 downloaded now ;-) Sonarr has around 223 continuing series... 
why is username/password obligatory?
would like not to use username/password, all is local not accessible from anywhere 

btw your video and how to install is also great. did not need it but it will work for everyone ;-)
will think about some features tonight ;-)

**Comment by l3uddz** [comment]
Thanks. Yeah the user and pass should be optional, I run it on a remote server so needed it for my use case but didn't consider others. Will add that to my list of things todo
